-- MySQL Script generated by MySQL Workbench
-- Mon 11 Sep 2023 12:05:18 AM +03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
    UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema atm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atm` DEFAULT CHARACTER SET utf8;
USE `atm`;
-- -----------------------------------------------------
-- Table `atm`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atm`.`Users` (
    `UserID` INT NOT NULL AUTO_INCREMENT,
    `UserName` VARCHAR(255) NOT NULL,
    `UserPwd` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`UserID`),
    UNIQUE INDEX `UserName_UNIQUE` (`UserName`) VISIBLE
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `atm`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atm`.`Accounts` (
    `AccountID` INT NOT NULL AUTO_INCREMENT,
    `UserName` VARCHAR(255) NOT NULL,
    `UserID` INT NULL,
    `CreationDate` VARCHAR(255) NOT NULL,
    `Country` VARCHAR(255) NOT NULL,
    `PhoneNo` VARCHAR(255) NOT NULL,
    `Balance` DOUBLE NOT NULL,
    `AccountType` VARCHAR(255) NULL,
    PRIMARY KEY (`AccountID`),
    UNIQUE INDEX `UserName_UNIQUE` (`UserName`) VISIBLE,
    INDEX `fk_Accounts_1_idx` (`UserName`, `UserID`) VISIBLE,
    CONSTRAINT `User-AccountsFK` FOREIGN KEY (`UserName`, `UserID`) REFERENCES `atm`.`Users` (`UserName`, `UserID`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `atm`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atm`.`Transactions` (
    `TransactionID` INT NOT NULL AUTO_INCREMENT,
    `UserName` VARCHAR(255) NOT NULL,
    `UserID` INT NULL,
    `AccountID` INT NULL,
    `TransactionAmt` DOUBLE NULL,
    PRIMARY KEY (`TransactionID`),
    UNIQUE INDEX `UserName_UNIQUE` (`UserName`) VISIBLE,
    INDEX `User-TransactionFK_idx` (`UserName`, `UserID`) VISIBLE,
    INDEX `Account-TransactionFK_idx` (`AccountID`) VISIBLE,
    CONSTRAINT `User-TransactionFK` FOREIGN KEY (`UserName`, `UserID`) REFERENCES `atm`.`Users` (`UserName`, `UserID`) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT `Account-TransactionFK` FOREIGN KEY (`AccountID`) REFERENCES `atm`.`Accounts` (`AccountID`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE = InnoDB;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
